/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookRouteImport } from './routes/book'
import { Route as LoungeRouteImport } from './routes/lounge'
import { Route as MeetRouteImport } from './routes/meet'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ApiKeepaliveRouteImport } from './routes/api/keepalive'
import { Route as ApiRemindersRouteImport } from './routes/api/reminders'
import { Route as CompaniesSlugRouteImport } from './routes/companies/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const LoungeRoute = LoungeRouteImport.update({
  id: '/lounge',
  path: '/lounge',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetRoute = MeetRouteImport.update({
  id: '/meet',
  path: '/meet',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeepaliveRoute = ApiKeepaliveRouteImport.update({
  id: '/api/keepalive',
  path: '/api/keepalive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemindersRoute = ApiRemindersRouteImport.update({
  id: '/api/reminders',
  path: '/api/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/lounge': typeof LoungeRoute
  '/meet': typeof MeetRoute
  '/schedule': typeof ScheduleRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/api/reminders': typeof ApiRemindersRoute
  '/companies/$slug': typeof CompaniesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/lounge': typeof LoungeRoute
  '/meet': typeof MeetRoute
  '/schedule': typeof ScheduleRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/api/reminders': typeof ApiRemindersRoute
  '/companies/$slug': typeof CompaniesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/lounge': typeof LoungeRoute
  '/meet': typeof MeetRoute
  '/schedule': typeof ScheduleRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/api/reminders': typeof ApiRemindersRoute
  '/companies/$slug': typeof CompaniesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/book'
    | '/lounge'
    | '/meet'
    | '/schedule'
    | '/api/keepalive'
    | '/api/reminders'
    | '/companies/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/book'
    | '/lounge'
    | '/meet'
    | '/schedule'
    | '/api/keepalive'
    | '/api/reminders'
    | '/companies/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book'
    | '/lounge'
    | '/meet'
    | '/schedule'
    | '/api/keepalive'
    | '/api/reminders'
    | '/companies/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookRoute: typeof BookRoute
  LoungeRoute: typeof LoungeRoute
  MeetRoute: typeof MeetRoute
  ScheduleRoute: typeof ScheduleRoute
  ApiKeepaliveRoute: typeof ApiKeepaliveRoute
  ApiRemindersRoute: typeof ApiRemindersRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lounge': {
      id: '/lounge'
      path: '/lounge'
      fullPath: '/lounge'
      preLoaderRoute: typeof LoungeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet': {
      id: '/meet'
      path: '/meet'
      fullPath: '/meet'
      preLoaderRoute: typeof MeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keepalive': {
      id: '/api/keepalive'
      path: '/api/keepalive'
      fullPath: '/api/keepalive'
      preLoaderRoute: typeof ApiKeepaliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reminders': {
      id: '/api/reminders'
      path: '/api/reminders'
      fullPath: '/api/reminders'
      preLoaderRoute: typeof ApiRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookRoute: BookRoute,
  LoungeRoute: LoungeRoute,
  MeetRoute: MeetRoute,
  ScheduleRoute: ScheduleRoute,
  ApiKeepaliveRoute: ApiKeepaliveRoute,
  ApiRemindersRoute: ApiRemindersRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
